FROM alpine:3.20@sha256:0a4eaa0eecf5f8c050e5bba433f58c052be7587ee8af3e8b3910ef9ab5fbe9f5 as otelc_curl
RUN apk --update add curl

FROM otel/opentelemetry-collector:latest@sha256:e5d8450fc1209b473b8d1c54a6e84b5c1583b8854828bf5f801323ec12c82ef1

COPY --from=otelc_curl / /

COPY ./otel-collector-config.yaml /etc/otel-collector-config.yaml
USER 0
RUN chmod o+r /etc/otel-collector-config.yaml
USER nobody
